"""phone models finished

Revision ID: a725fd9de26c
Revises: 4ee0aa486777
Create Date: 2025-12-02 16:24:07.887199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a725fd9de26c'
down_revision: Union[str, Sequence[str], None] = '4ee0aa486777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battery',
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('fast_charging', sa.Boolean(), nullable=False),
    sa.Column('wireless_charging', sa.Boolean(), nullable=False),
    sa.Column('charging_connector', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('country_of_origin',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone_screen',
    sa.Column('display_size', sa.Float(), nullable=False),
    sa.Column('refresh_rate', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage',
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone_model',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone',
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('battery_id', sa.Integer(), nullable=False),
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.Column('oc_version', sa.String(), nullable=False),
    sa.Column('cpu', sa.String(), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('cpu_frequency', sa.Integer(), nullable=False),
    sa.Column('gpu', sa.String(), nullable=False),
    sa.Column('ram', sa.Integer(), nullable=False),
    sa.Column('storage_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Enum('NEW', 'USED', 'BROKEN', name='phone_condition'), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('country_of_origin_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['battery_id'], ['battery.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['country_of_origin_id'], ['country_of_origin.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['phone_model.id'], ),
    sa.ForeignKeyConstraint(['screen_id'], ['phone_screen.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['storage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone_image',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('phone_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['phone_id'], ['phone.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_image')
    op.drop_table('phone')
    op.drop_table('phone_model')
    op.drop_table('storage')
    op.drop_table('phone_screen')
    op.drop_table('country_of_origin')
    op.drop_table('brand')
    op.drop_table('battery')
    # ### end Alembic commands ###
