"""user role column added

Revision ID: 75e5a01c74ed
Revises: 07d067e2872f
Create Date: 2025-11-30 13:43:06.757184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e5a01c74ed'
down_revision: Union[str, Sequence[str], None] = '07d067e2872f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
            'user',sa.Column(
                'role',
                sa.Enum('USER', 'ADMIN', name='userrole'),
                nullable=False,
                server_default='user',
                )
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
